version: '3'

services:
  focalboard:
    image: mattermost/focalboard:latest
    container_name: focalboard
    ports:
      - "8000:8000"
    volumes:
      - focalboard-data:/opt/focalboard/data
    restart: unless-stopped

volumes:
  focalboard-data: