name: Terraform Infra

on:
 push:
permissions:
  id-token: write
  contents: read
jobs:
  provision:
    name: Terraform Infra via EC2
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
 
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.ROLE }}
          aws-region: us-east-1
 
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.11.4'
          
      - name: Terraform formtat
        run: terraform fmt
        

      - name: Terraform init
        run: terraform init
      
      - name: Terraform test
        run: |
          terraform test
        continue-on-error: true

      - name: Install Checkov
        run: |
          python3 -m pip install --upgrade pip
          pip install checkov

      - name: Run Checkov Scan
        run: checkov -d ./ --skip-path .github/* --soft-fail
        
      - name: Terraform validate 
        run: terraform validate 

      - name: Terraform plan
        run: terraform plan
        
      - name: Install tflint
        run: |
             curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: Run tflint with custom config
        run: |
          echo "Using custom rules from .tflint.hcl"
          tflint --config=./.tflint.hcl
        continue-on-error: true

      - name: Install Conftest
        run: |
          wget https://github.com/open-policy-agent/conftest/releases/latest/download/conftest_Linux_x86_64.tar.gz
          tar xzf conftest_Linux_x86_64.tar.gz
          sudo mv conftest /usr/local/bin
      
      - name: Run OPA Policy Check
        run: |
          conftest test tfplan.json --policy policies/first.rego
     
          
      - name: Terraform Apply (Create EC2)
        run: terraform apply -auto-approve
        